#!/usr/bin/env bash
# Installs Nginx web server with configure it:
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

# change the owner of the /var/www directory to the current user recursively
sudo chown -R $USER /var/www

# set up a page containing "Hello World" when queried
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# restart Nginx to apply the changes
service nginx start
