#!/usr/bin/env bash
# Bash script that installs Nginx server

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" |sudo tee /var/www/html/index.html
sudo service nginx restart
sudo service nginx reload
