#!/usr/bin/env bash
# rite a Bash script that displays the time for 12 hours and 59 minutes

hou=0
while [ $hou -le 12 ]
do
	echo "Hour: $hou"
	min=0
	while [ $min -le 60 ]
	do
		echo $min
		min=$((min + 1))
	done
	hour=$(( hou + 1 ))
done

