#!/usr/bin/env bash
# rite a Bash script that displays the time for 12 hours and 59 minutes

hou=0
while [ $hou -lt 13 ]
do
	echo "Hour: $hou"
	min=1
	while [ $min -le 59 ]
	do
		echo $min
		min=$((min + 1))
	done
	hou=$(( hou + 1 ))
done

